# CI/CD for internal operations
---
stages:
- build
- test
- deploy/rc
- integration
- deploy/stable

variables:
  GIT_SUBMODULE_STRATEGY: recursive


test:
  image: python:${PYTHON_VERSION}
  services:
    - name: redis:latest
      alias: redis
  stage: test
  variables:
    RQ_TESTS_REDIS_HOST: redis
  before_script:
  - pip install -e .
  - pip install pytest-cov sentry-sdk codecov pytest mock
  script:
  - RUN_SLOW_TESTS_TOO=1 py.test --cov rq --durations=5
  coverage: "/TOTAL.+ ([0-9]{1,3}%)/"
  allow_failure: true
  parallel:
    matrix:
      - PYTHON_VERSION: ["3.5", "3.6", "3.7", "3.8"]
        DUMMY_VARIABLE: ["1"]
  tags:
  - os/linux
  - type/docker
